services:
  mcp_server:
    image: mcp_server
    ports:
      - "7126:8080"
  orchestrator:
    image: orchestrator
    depends_on:
      - hub
  teamsagent:
    image: teamsagent
    depends_on:
      - orchestrator
networks:
  default:
