/* 
 * The Blue Alliance API v3
 *
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
 *
 * The version of the OpenAPI document: 3.8.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

namespace TBAAPI.V3Client.Model;

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
/// <summary>
/// OPR, DPR, and CCWM for teams at the event.
/// </summary>
/// <remarks>
/// Initializes a new instance of the <see cref="EventOPRs" /> class.
/// </remarks>
[DataContract]
public partial record EventOPRs : IValidatableObject
{

    /// <summary>
    /// A key-value pair with team key (eg 'frc254') as key and OPR as value.
    /// </summary>
    /// <value>A key-value pair with team key (eg 'frc254') as key and OPR as value.</value>
    [DataMember(Name = "oprs", EmitDefaultValue = false), JsonPropertyName("oprs")]
    public IDictionary<string, float>? Oprs { get; set; }

    /// <summary>
    /// A key-value pair with team key (eg 'frc254') as key and DPR as value.
    /// </summary>
    /// <value>A key-value pair with team key (eg 'frc254') as key and DPR as value.</value>
    [DataMember(Name = "dprs", EmitDefaultValue = false), JsonPropertyName("dprs")]
    public IDictionary<string, float>? Dprs { get; set; }

    /// <summary>
    /// A key-value pair with team key (eg 'frc254') as key and CCWM as value.
    /// </summary>
    /// <value>A key-value pair with team key (eg 'frc254') as key and CCWM as value.</value>
    [DataMember(Name = "ccwms", EmitDefaultValue = false), JsonPropertyName("ccwms")]
    public IDictionary<string, float>? Ccwms { get; set; }

    /// <summary>
    /// Returns the string presentation of the object
    /// </summary>
    /// <returns>String presentation of the object</returns>
    public override string ToString()
    {
        var sb = new StringBuilder();
        sb.Append("class EventOPRs {\n");
        sb.Append("  Oprs: ").Append(this.Oprs).Append('\n');
        sb.Append("  Dprs: ").Append(this.Dprs).Append('\n');
        sb.Append("  Ccwms: ").Append(this.Ccwms).Append('\n');
        sb.Append("}\n");
        return sb.ToString();
    }

    /// <summary>
    /// Returns the JSON string presentation of the object
    /// </summary>
    /// <returns>JSON string presentation of the object</returns>
    public virtual string ToJson() => JsonSerializer.Serialize(this, GetType());

    /// <summary>
    /// Gets the hash code
    /// </summary>
    /// <returns>Hash code</returns>
    public override int GetHashCode()
    {
        unchecked // Overflow is fine, just wrap
        {
            var hashCode = 41;
            if (this.Oprs is not null)
            {
                hashCode = (hashCode * 59) + this.Oprs.GetHashCode();
            }

            if (this.Dprs is not null)
            {
                hashCode = (hashCode * 59) + this.Dprs.GetHashCode();
            }

            if (this.Ccwms is not null)
            {
                hashCode = (hashCode * 59) + this.Ccwms.GetHashCode();
            }

            return hashCode;
        }
    }

    /// <summary>
    /// To validate all properties of the instance
    /// </summary>
    /// <param name="validationContext">Validation context</param>
    /// <returns>Validation Result</returns>
    IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext) => [];
}
