/* 
 * The Blue Alliance API v3
 *
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
 *
 * The version of the OpenAPI document: 3.8.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

namespace TBAAPI.V3Client.Model;

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
/// <summary>
/// Timeseries data for the 2018 game *FIRST* POWER UP. *WARNING:* This is *not* official data, and is subject to a significant possibility of error, or missing data. Do not rely on this data for any purpose. In fact, pretend we made it up. *WARNING:* This model is currently under active development and may change at any time, including in breaking ways.
/// </summary>
/// <remarks>
/// Initializes a new instance of the <see cref="MatchTimeseries2018" /> class.
/// </remarks>
[DataContract]
public partial record MatchTimeseries2018 : IValidatableObject
{

    /// <summary>
    /// TBA event key with the format yyyy[EVENT_CODE], where yyyy is the year, and EVENT_CODE is the event code of the event.
    /// </summary>
    /// <value>TBA event key with the format yyyy[EVENT_CODE], where yyyy is the year, and EVENT_CODE is the event code of the event.</value>
    [DataMember(Name = "event_key", EmitDefaultValue = false), JsonPropertyName("event_key")]
    public string? EventKey { get; set; }

    /// <summary>
    /// Match ID consisting of the level, match number, and set number, eg 'qm45' or 'f1m1'.
    /// </summary>
    /// <value>Match ID consisting of the level, match number, and set number, eg 'qm45' or 'f1m1'.</value>
    [DataMember(Name = "match_id", EmitDefaultValue = false), JsonPropertyName("match_id")]
    public string? MatchId { get; set; }

    /// <summary>
    /// Current mode of play, can be 'pre_match', 'auto', 'telop', or 'post_match'.
    /// </summary>
    /// <value>Current mode of play, can be 'pre_match', 'auto', 'telop', or 'post_match'.</value>
    [DataMember(Name = "mode", EmitDefaultValue = false), JsonPropertyName("mode")]
    public string? Mode { get; set; }

    /// <summary>
    /// Gets or Sets Play
    /// </summary>
    [DataMember(Name = "play", EmitDefaultValue = false), JsonPropertyName("play")]
    public int Play { get; set; }

    /// <summary>
    /// Amount of time remaining in the match, only valid during 'auto' and 'teleop' modes.
    /// </summary>
    /// <value>Amount of time remaining in the match, only valid during 'auto' and 'teleop' modes.</value>
    [DataMember(Name = "time_remaining", EmitDefaultValue = false), JsonPropertyName("time_remaining")]
    public int TimeRemaining { get; set; }

    /// <summary>
    /// 1 if the blue alliance is credited with the AUTO QUEST, 0 if not.
    /// </summary>
    /// <value>1 if the blue alliance is credited with the AUTO QUEST, 0 if not.</value>
    [DataMember(Name = "blue_auto_quest", EmitDefaultValue = false), JsonPropertyName("blue_auto_quest")]
    public int BlueAutoQuest { get; set; }

    /// <summary>
    /// Number of POWER CUBES in the BOOST section of the blue alliance VAULT.
    /// </summary>
    /// <value>Number of POWER CUBES in the BOOST section of the blue alliance VAULT.</value>
    [DataMember(Name = "blue_boost_count", EmitDefaultValue = false), JsonPropertyName("blue_boost_count")]
    public int BlueBoostCount { get; set; }

    /// <summary>
    /// Returns 1 if the blue alliance BOOST was played, or 0 if not played.
    /// </summary>
    /// <value>Returns 1 if the blue alliance BOOST was played, or 0 if not played.</value>
    [DataMember(Name = "blue_boost_played", EmitDefaultValue = false), JsonPropertyName("blue_boost_played")]
    public int BlueBoostPlayed { get; set; }

    /// <summary>
    /// Name of the current blue alliance POWER UP being played, or 'null'.
    /// </summary>
    /// <value>Name of the current blue alliance POWER UP being played, or 'null'.</value>
    [DataMember(Name = "blue_current_powerup", EmitDefaultValue = false), JsonPropertyName("blue_current_powerup")]
    public string? BlueCurrentPowerup { get; set; }

    /// <summary>
    /// 1 if the blue alliance is credited with FACING THE BOSS, 0 if not.
    /// </summary>
    /// <value>1 if the blue alliance is credited with FACING THE BOSS, 0 if not.</value>
    [DataMember(Name = "blue_face_the_boss", EmitDefaultValue = false), JsonPropertyName("blue_face_the_boss")]
    public int BlueFaceTheBoss { get; set; }

    /// <summary>
    /// Number of POWER CUBES in the FORCE section of the blue alliance VAULT.
    /// </summary>
    /// <value>Number of POWER CUBES in the FORCE section of the blue alliance VAULT.</value>
    [DataMember(Name = "blue_force_count", EmitDefaultValue = false), JsonPropertyName("blue_force_count")]
    public int BlueForceCount { get; set; }

    /// <summary>
    /// Returns 1 if the blue alliance FORCE was played, or 0 if not played.
    /// </summary>
    /// <value>Returns 1 if the blue alliance FORCE was played, or 0 if not played.</value>
    [DataMember(Name = "blue_force_played", EmitDefaultValue = false), JsonPropertyName("blue_force_played")]
    public int BlueForcePlayed { get; set; }

    /// <summary>
    /// Number of POWER CUBES in the LEVITATE section of the blue alliance VAULT.
    /// </summary>
    /// <value>Number of POWER CUBES in the LEVITATE section of the blue alliance VAULT.</value>
    [DataMember(Name = "blue_levitate_count", EmitDefaultValue = false), JsonPropertyName("blue_levitate_count")]
    public int BlueLevitateCount { get; set; }

    /// <summary>
    /// Returns 1 if the blue alliance LEVITATE was played, or 0 if not played.
    /// </summary>
    /// <value>Returns 1 if the blue alliance LEVITATE was played, or 0 if not played.</value>
    [DataMember(Name = "blue_levitate_played", EmitDefaultValue = false), JsonPropertyName("blue_levitate_played")]
    public int BlueLevitatePlayed { get; set; }

    /// <summary>
    /// Number of seconds remaining in the blue alliance POWER UP time, or 0 if none is active.
    /// </summary>
    /// <value>Number of seconds remaining in the blue alliance POWER UP time, or 0 if none is active.</value>
    [DataMember(Name = "blue_powerup_time_remaining", EmitDefaultValue = false), JsonPropertyName("blue_powerup_time_remaining")]
    public string? BluePowerupTimeRemaining { get; set; }

    /// <summary>
    /// 1 if the blue alliance owns the SCALE, 0 if not.
    /// </summary>
    /// <value>1 if the blue alliance owns the SCALE, 0 if not.</value>
    [DataMember(Name = "blue_scale_owned", EmitDefaultValue = false), JsonPropertyName("blue_scale_owned")]
    public int BlueScaleOwned { get; set; }

    /// <summary>
    /// Current score for the blue alliance.
    /// </summary>
    /// <value>Current score for the blue alliance.</value>
    [DataMember(Name = "blue_score", EmitDefaultValue = false), JsonPropertyName("blue_score")]
    public int BlueScore { get; set; }

    /// <summary>
    /// 1 if the blue alliance owns their SWITCH, 0 if not.
    /// </summary>
    /// <value>1 if the blue alliance owns their SWITCH, 0 if not.</value>
    [DataMember(Name = "blue_switch_owned", EmitDefaultValue = false), JsonPropertyName("blue_switch_owned")]
    public int BlueSwitchOwned { get; set; }

    /// <summary>
    /// 1 if the red alliance is credited with the AUTO QUEST, 0 if not.
    /// </summary>
    /// <value>1 if the red alliance is credited with the AUTO QUEST, 0 if not.</value>
    [DataMember(Name = "red_auto_quest", EmitDefaultValue = false), JsonPropertyName("red_auto_quest")]
    public int RedAutoQuest { get; set; }

    /// <summary>
    /// Number of POWER CUBES in the BOOST section of the red alliance VAULT.
    /// </summary>
    /// <value>Number of POWER CUBES in the BOOST section of the red alliance VAULT.</value>
    [DataMember(Name = "red_boost_count", EmitDefaultValue = false), JsonPropertyName("red_boost_count")]
    public int RedBoostCount { get; set; }

    /// <summary>
    /// Returns 1 if the red alliance BOOST was played, or 0 if not played.
    /// </summary>
    /// <value>Returns 1 if the red alliance BOOST was played, or 0 if not played.</value>
    [DataMember(Name = "red_boost_played", EmitDefaultValue = false), JsonPropertyName("red_boost_played")]
    public int RedBoostPlayed { get; set; }

    /// <summary>
    /// Name of the current red alliance POWER UP being played, or 'null'.
    /// </summary>
    /// <value>Name of the current red alliance POWER UP being played, or 'null'.</value>
    [DataMember(Name = "red_current_powerup", EmitDefaultValue = false), JsonPropertyName("red_current_powerup")]
    public string? RedCurrentPowerup { get; set; }

    /// <summary>
    /// 1 if the red alliance is credited with FACING THE BOSS, 0 if not.
    /// </summary>
    /// <value>1 if the red alliance is credited with FACING THE BOSS, 0 if not.</value>
    [DataMember(Name = "red_face_the_boss", EmitDefaultValue = false), JsonPropertyName("red_face_the_boss")]
    public int RedFaceTheBoss { get; set; }

    /// <summary>
    /// Number of POWER CUBES in the FORCE section of the red alliance VAULT.
    /// </summary>
    /// <value>Number of POWER CUBES in the FORCE section of the red alliance VAULT.</value>
    [DataMember(Name = "red_force_count", EmitDefaultValue = false), JsonPropertyName("red_force_count")]
    public int RedForceCount { get; set; }

    /// <summary>
    /// Returns 1 if the red alliance FORCE was played, or 0 if not played.
    /// </summary>
    /// <value>Returns 1 if the red alliance FORCE was played, or 0 if not played.</value>
    [DataMember(Name = "red_force_played", EmitDefaultValue = false), JsonPropertyName("red_force_played")]
    public int RedForcePlayed { get; set; }

    /// <summary>
    /// Number of POWER CUBES in the LEVITATE section of the red alliance VAULT.
    /// </summary>
    /// <value>Number of POWER CUBES in the LEVITATE section of the red alliance VAULT.</value>
    [DataMember(Name = "red_levitate_count", EmitDefaultValue = false), JsonPropertyName("red_levitate_count")]
    public int RedLevitateCount { get; set; }

    /// <summary>
    /// Returns 1 if the red alliance LEVITATE was played, or 0 if not played.
    /// </summary>
    /// <value>Returns 1 if the red alliance LEVITATE was played, or 0 if not played.</value>
    [DataMember(Name = "red_levitate_played", EmitDefaultValue = false), JsonPropertyName("red_levitate_played")]
    public int RedLevitatePlayed { get; set; }

    /// <summary>
    /// Number of seconds remaining in the red alliance POWER UP time, or 0 if none is active.
    /// </summary>
    /// <value>Number of seconds remaining in the red alliance POWER UP time, or 0 if none is active.</value>
    [DataMember(Name = "red_powerup_time_remaining", EmitDefaultValue = false), JsonPropertyName("red_powerup_time_remaining")]
    public string? RedPowerupTimeRemaining { get; set; }

    /// <summary>
    /// 1 if the red alliance owns the SCALE, 0 if not.
    /// </summary>
    /// <value>1 if the red alliance owns the SCALE, 0 if not.</value>
    [DataMember(Name = "red_scale_owned", EmitDefaultValue = false), JsonPropertyName("red_scale_owned")]
    public int RedScaleOwned { get; set; }

    /// <summary>
    /// Current score for the red alliance.
    /// </summary>
    /// <value>Current score for the red alliance.</value>
    [DataMember(Name = "red_score", EmitDefaultValue = false), JsonPropertyName("red_score")]
    public int RedScore { get; set; }

    /// <summary>
    /// 1 if the red alliance owns their SWITCH, 0 if not.
    /// </summary>
    /// <value>1 if the red alliance owns their SWITCH, 0 if not.</value>
    [DataMember(Name = "red_switch_owned", EmitDefaultValue = false), JsonPropertyName("red_switch_owned")]
    public int RedSwitchOwned { get; set; }

    /// <summary>
    /// Returns the string presentation of the object
    /// </summary>
    /// <returns>String presentation of the object</returns>
    public override string ToString()
    {
        var sb = new StringBuilder();
        sb.Append("class MatchTimeseries2018 {\n");
        sb.Append("  EventKey: ").Append(this.EventKey).Append('\n');
        sb.Append("  MatchId: ").Append(this.MatchId).Append('\n');
        sb.Append("  Mode: ").Append(this.Mode).Append('\n');
        sb.Append("  Play: ").Append(this.Play).Append('\n');
        sb.Append("  TimeRemaining: ").Append(this.TimeRemaining).Append('\n');
        sb.Append("  BlueAutoQuest: ").Append(this.BlueAutoQuest).Append('\n');
        sb.Append("  BlueBoostCount: ").Append(this.BlueBoostCount).Append('\n');
        sb.Append("  BlueBoostPlayed: ").Append(this.BlueBoostPlayed).Append('\n');
        sb.Append("  BlueCurrentPowerup: ").Append(this.BlueCurrentPowerup).Append('\n');
        sb.Append("  BlueFaceTheBoss: ").Append(this.BlueFaceTheBoss).Append('\n');
        sb.Append("  BlueForceCount: ").Append(this.BlueForceCount).Append('\n');
        sb.Append("  BlueForcePlayed: ").Append(this.BlueForcePlayed).Append('\n');
        sb.Append("  BlueLevitateCount: ").Append(this.BlueLevitateCount).Append('\n');
        sb.Append("  BlueLevitatePlayed: ").Append(this.BlueLevitatePlayed).Append('\n');
        sb.Append("  BluePowerupTimeRemaining: ").Append(this.BluePowerupTimeRemaining).Append('\n');
        sb.Append("  BlueScaleOwned: ").Append(this.BlueScaleOwned).Append('\n');
        sb.Append("  BlueScore: ").Append(this.BlueScore).Append('\n');
        sb.Append("  BlueSwitchOwned: ").Append(this.BlueSwitchOwned).Append('\n');
        sb.Append("  RedAutoQuest: ").Append(this.RedAutoQuest).Append('\n');
        sb.Append("  RedBoostCount: ").Append(this.RedBoostCount).Append('\n');
        sb.Append("  RedBoostPlayed: ").Append(this.RedBoostPlayed).Append('\n');
        sb.Append("  RedCurrentPowerup: ").Append(this.RedCurrentPowerup).Append('\n');
        sb.Append("  RedFaceTheBoss: ").Append(this.RedFaceTheBoss).Append('\n');
        sb.Append("  RedForceCount: ").Append(this.RedForceCount).Append('\n');
        sb.Append("  RedForcePlayed: ").Append(this.RedForcePlayed).Append('\n');
        sb.Append("  RedLevitateCount: ").Append(this.RedLevitateCount).Append('\n');
        sb.Append("  RedLevitatePlayed: ").Append(this.RedLevitatePlayed).Append('\n');
        sb.Append("  RedPowerupTimeRemaining: ").Append(this.RedPowerupTimeRemaining).Append('\n');
        sb.Append("  RedScaleOwned: ").Append(this.RedScaleOwned).Append('\n');
        sb.Append("  RedScore: ").Append(this.RedScore).Append('\n');
        sb.Append("  RedSwitchOwned: ").Append(this.RedSwitchOwned).Append('\n');
        sb.Append("}\n");
        return sb.ToString();
    }

    /// <summary>
    /// Returns the JSON string presentation of the object
    /// </summary>
    /// <returns>JSON string presentation of the object</returns>
    public virtual string ToJson() => JsonSerializer.Serialize(this, GetType());

    /// <summary>
    /// Gets the hash code
    /// </summary>
    /// <returns>Hash code</returns>
    public override int GetHashCode()
    {
        unchecked // Overflow is fine, just wrap
        {
            var hashCode = 41;
            if (this.EventKey is not null)
            {
                hashCode = (hashCode * 59) + this.EventKey.GetHashCode();
            }

            if (this.MatchId is not null)
            {
                hashCode = (hashCode * 59) + this.MatchId.GetHashCode();
            }

            if (this.Mode is not null)
            {
                hashCode = (hashCode * 59) + this.Mode.GetHashCode();
            }

            hashCode = (hashCode * 59) + this.Play.GetHashCode();
            hashCode = (hashCode * 59) + this.TimeRemaining.GetHashCode();
            hashCode = (hashCode * 59) + this.BlueAutoQuest.GetHashCode();
            hashCode = (hashCode * 59) + this.BlueBoostCount.GetHashCode();
            hashCode = (hashCode * 59) + this.BlueBoostPlayed.GetHashCode();
            if (this.BlueCurrentPowerup is not null)
            {
                hashCode = (hashCode * 59) + this.BlueCurrentPowerup.GetHashCode();
            }

            hashCode = (hashCode * 59) + this.BlueFaceTheBoss.GetHashCode();
            hashCode = (hashCode * 59) + this.BlueForceCount.GetHashCode();
            hashCode = (hashCode * 59) + this.BlueForcePlayed.GetHashCode();
            hashCode = (hashCode * 59) + this.BlueLevitateCount.GetHashCode();
            hashCode = (hashCode * 59) + this.BlueLevitatePlayed.GetHashCode();
            if (this.BluePowerupTimeRemaining is not null)
            {
                hashCode = (hashCode * 59) + this.BluePowerupTimeRemaining.GetHashCode();
            }

            hashCode = (hashCode * 59) + this.BlueScaleOwned.GetHashCode();
            hashCode = (hashCode * 59) + this.BlueScore.GetHashCode();
            hashCode = (hashCode * 59) + this.BlueSwitchOwned.GetHashCode();
            hashCode = (hashCode * 59) + this.RedAutoQuest.GetHashCode();
            hashCode = (hashCode * 59) + this.RedBoostCount.GetHashCode();
            hashCode = (hashCode * 59) + this.RedBoostPlayed.GetHashCode();
            if (this.RedCurrentPowerup is not null)
            {
                hashCode = (hashCode * 59) + this.RedCurrentPowerup.GetHashCode();
            }

            hashCode = (hashCode * 59) + this.RedFaceTheBoss.GetHashCode();
            hashCode = (hashCode * 59) + this.RedForceCount.GetHashCode();
            hashCode = (hashCode * 59) + this.RedForcePlayed.GetHashCode();
            hashCode = (hashCode * 59) + this.RedLevitateCount.GetHashCode();
            hashCode = (hashCode * 59) + this.RedLevitatePlayed.GetHashCode();
            if (this.RedPowerupTimeRemaining is not null)
            {
                hashCode = (hashCode * 59) + this.RedPowerupTimeRemaining.GetHashCode();
            }

            hashCode = (hashCode * 59) + this.RedScaleOwned.GetHashCode();
            hashCode = (hashCode * 59) + this.RedScore.GetHashCode();
            hashCode = (hashCode * 59) + this.RedSwitchOwned.GetHashCode();
            return hashCode;
        }
    }

    /// <summary>
    /// To validate all properties of the instance
    /// </summary>
    /// <param name="validationContext">Validation context</param>
    /// <returns>Validation Result</returns>
    IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext) => [];
}
