/* 
 * The Blue Alliance API v3
 *
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
 *
 * The version of the OpenAPI document: 3.8.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

namespace TBAAPI.V3Client.Model;

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
/// <summary>
/// EventRanking
/// </summary>
[DataContract]
public partial record EventRanking : IValidatableObject
{
    /// <summary>
    /// List of rankings at the event.
    /// </summary>
    /// <value>List of rankings at the event.</value>
    [DataMember(Name = "rankings", EmitDefaultValue = false), JsonPropertyName("rankings")]
    public IList<EventRankingRankings>? Rankings { get; set; }

    /// <summary>
    /// List of special TBA-generated values provided in the 'extra_stats' array for each item.
    /// </summary>
    /// <value>List of special TBA-generated values provided in the 'extra_stats' array for each item.</value>
    [DataMember(Name = "extra_stats_info", EmitDefaultValue = false), JsonPropertyName("extra_stats_info")]
    public IList<EventRankingExtraStatsInfo>? ExtraStatsInfo { get; set; }

    /// <summary>
    /// List of year-specific values provided in the 'sort_orders' array for each team.
    /// </summary>
    /// <value>List of year-specific values provided in the 'sort_orders' array for each team.</value>
    [DataMember(Name = "sort_order_info", EmitDefaultValue = false), JsonPropertyName("sort_order_info")]
    public IList<EventRankingSortOrderInfo>? SortOrderInfo { get; set; }

    /// <summary>
    /// Returns the string presentation of the object
    /// </summary>
    /// <returns>String presentation of the object</returns>
    public override string ToString()
    {
        var sb = new StringBuilder();
        sb.Append("class EventRanking {\n");
        sb.Append("  Rankings: ").Append(this.Rankings).Append('\n');
        sb.Append("  ExtraStatsInfo: ").Append(this.ExtraStatsInfo).Append('\n');
        sb.Append("  SortOrderInfo: ").Append(this.SortOrderInfo).Append('\n');
        sb.Append("}\n");
        return sb.ToString();
    }

    /// <summary>
    /// Returns the JSON string presentation of the object
    /// </summary>
    /// <returns>JSON string presentation of the object</returns>
    public virtual string ToJson() => JsonSerializer.Serialize(this, GetType());

    /// <summary>
    /// Gets the hash code
    /// </summary>
    /// <returns>Hash code</returns>
    public override int GetHashCode()
    {
        unchecked // Overflow is fine, just wrap
        {
            var hashCode = 41;
            if (this.Rankings is not null)
            {
                hashCode = (hashCode * 59) + this.Rankings.GetHashCode();
            }

            if (this.ExtraStatsInfo is not null)
            {
                hashCode = (hashCode * 59) + this.ExtraStatsInfo.GetHashCode();
            }

            if (this.SortOrderInfo is not null)
            {
                hashCode = (hashCode * 59) + this.SortOrderInfo.GetHashCode();
            }

            return hashCode;
        }
    }

    /// <summary>
    /// To validate all properties of the instance
    /// </summary>
    /// <param name="validationContext">Validation context</param>
    /// <returns>Validation Result</returns>
    IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext) => [];
}
