/* 
 * The Blue Alliance API v3
 *
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
 *
 * The version of the OpenAPI document: 3.8.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

namespace TBAAPI.V3Client.Model;

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;

/// <summary>
/// Award
/// </summary>
[DataContract]
public partial record Award : IValidatableObject
{
    /// <summary>
    /// The name of the award as provided by FIRST. May vary for the same award type.
    /// </summary>
    /// <value>The name of the award as provided by FIRST. May vary for the same award type.</value>
    [DataMember(Name = "name", EmitDefaultValue = false), JsonPropertyName("name")]
    public string? Name { get; set; }

    /// <summary>
    /// Type of award given. See https://github.com/the-blue-alliance/the-blue-alliance/blob/master/consts/award_type.py#L6
    /// </summary>
    /// <value>Type of award given. See https://github.com/the-blue-alliance/the-blue-alliance/blob/master/consts/award_type.py#L6</value>
    [DataMember(Name = "award_type", EmitDefaultValue = false), JsonPropertyName("award_type")]
    public int AwardType { get; set; }

    /// <summary>
    /// The event_key of the event the award was won at.
    /// </summary>
    /// <value>The event_key of the event the award was won at.</value>
    [DataMember(Name = "event_key", EmitDefaultValue = false), JsonPropertyName("event_key")]
    public string? EventKey { get; set; }

    /// <summary>
    /// A list of recipients of the award at the event. May have either a team_key or an awardee, both, or neither (in the case the award wasn&#39;t awarded at the event).
    /// </summary>
    /// <value>A list of recipients of the award at the event. May have either a team_key or an awardee, both, or neither (in the case the award wasn&#39;t awarded at the event).</value>
    [DataMember(Name = "recipient_list", EmitDefaultValue = false), JsonPropertyName("recipient_list")]
    public IList<AwardRecipient>? RecipientList { get; set; }

    /// <summary>
    /// The year this award was won.
    /// </summary>
    /// <value>The year this award was won.</value>
    [DataMember(Name = "year", EmitDefaultValue = false), JsonPropertyName("year")]
    public int Year { get; set; }

    /// <summary>
    /// Returns the string presentation of the object
    /// </summary>
    /// <returns>String presentation of the object</returns>
    public override string ToString()
    {
        var sb = new StringBuilder();
        sb.Append("class Award {\n");
        sb.Append("  Name: ").Append(this.Name).Append('\n');
        sb.Append("  AwardType: ").Append(this.AwardType).Append('\n');
        sb.Append("  EventKey: ").Append(this.EventKey).Append('\n');
        sb.Append("  RecipientList: ").Append(this.RecipientList).Append('\n');
        sb.Append("  Year: ").Append(this.Year).Append('\n');
        sb.Append("}\n");
        return sb.ToString();
    }

    /// <summary>
    /// Returns the JSON string presentation of the object
    /// </summary>
    /// <returns>JSON string presentation of the object</returns>
    public virtual string ToJson() => JsonSerializer.Serialize(this, GetType());

    /// <summary>
    /// Gets the hash code
    /// </summary>
    /// <returns>Hash code</returns>
    public override int GetHashCode()
    {
        unchecked // Overflow is fine, just wrap
        {
            var hashCode = 41;
            if (this.Name is not null)
            {
                hashCode = (hashCode * 59) + this.Name.GetHashCode();
            }

            hashCode = (hashCode * 59) + this.AwardType.GetHashCode();
            if (this.EventKey is not null)
            {
                hashCode = (hashCode * 59) + this.EventKey.GetHashCode();
            }

            if (this.RecipientList is not null)
            {
                hashCode = (hashCode * 59) + this.RecipientList.GetHashCode();
            }

            hashCode = (hashCode * 59) + this.Year.GetHashCode();
            return hashCode;
        }
    }

    /// <summary>
    /// To validate all properties of the instance
    /// </summary>
    /// <param name="validationContext">Validation context</param>
    /// <returns>Validation Result</returns>
    IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext) => [];
}
