/* 
 * The Blue Alliance API v3
 *
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
 *
 * The version of the OpenAPI document: 3.8.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

namespace TBAAPI.V3Client.Model;

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
/// <summary>
/// Rank of a team in a district.
/// </summary>
[DataContract]
public partial record DistrictRanking : IValidatableObject
{
    /// <summary>
    /// TBA team key for the team.
    /// </summary>
    /// <value>TBA team key for the team.</value>
    [DataMember(Name = "team_key", EmitDefaultValue = false), JsonPropertyName("team_key")]
    public string? TeamKey { get; set; }

    /// <summary>
    /// Numerical rank of the team, 1 being top rank.
    /// </summary>
    /// <value>Numerical rank of the team, 1 being top rank.</value>
    [DataMember(Name = "rank", EmitDefaultValue = false), JsonPropertyName("rank")]
    public int Rank { get; set; }

    /// <summary>
    /// Any points added to a team as a result of the rookie bonus.
    /// </summary>
    /// <value>Any points added to a team as a result of the rookie bonus.</value>
    [DataMember(Name = "rookie_bonus", EmitDefaultValue = false), JsonPropertyName("rookie_bonus")]
    public int RookieBonus { get; set; }

    /// <summary>
    /// Total district points for the team.
    /// </summary>
    /// <value>Total district points for the team.</value>
    [DataMember(Name = "point_total", EmitDefaultValue = false), JsonPropertyName("point_total")]
    public int PointTotal { get; set; }

    /// <summary>
    /// List of events that contributed to the point total for the team.
    /// </summary>
    /// <value>List of events that contributed to the point total for the team.</value>
    [DataMember(Name = "event_points", EmitDefaultValue = false), JsonPropertyName("event_points")]
    public IList<DistrictRankingEventPoints>? EventPoints { get; set; }

    /// <summary>
    /// Returns the string presentation of the object
    /// </summary>
    /// <returns>String presentation of the object</returns>
    public override string ToString()
    {
        var sb = new StringBuilder();
        sb.Append("class DistrictRanking {\n");
        sb.Append("  TeamKey: ").Append(this.TeamKey).Append('\n');
        sb.Append("  Rank: ").Append(this.Rank).Append('\n');
        sb.Append("  RookieBonus: ").Append(this.RookieBonus).Append('\n');
        sb.Append("  PointTotal: ").Append(this.PointTotal).Append('\n');
        sb.Append("  EventPoints: ").Append(this.EventPoints).Append('\n');
        sb.Append("}\n");
        return sb.ToString();
    }

    /// <summary>
    /// Returns the JSON string presentation of the object
    /// </summary>
    /// <returns>JSON string presentation of the object</returns>
    public virtual string ToJson() => JsonSerializer.Serialize(this, GetType());

    /// <summary>
    /// Gets the hash code
    /// </summary>
    /// <returns>Hash code</returns>
    public override int GetHashCode()
    {
        unchecked // Overflow is fine, just wrap
        {
            var hashCode = 41;
            if (this.TeamKey is not null)
            {
                hashCode = (hashCode * 59) + this.TeamKey.GetHashCode();
            }

            hashCode = (hashCode * 59) + this.Rank.GetHashCode();
            hashCode = (hashCode * 59) + this.RookieBonus.GetHashCode();
            hashCode = (hashCode * 59) + this.PointTotal.GetHashCode();
            if (this.EventPoints is not null)
            {
                hashCode = (hashCode * 59) + this.EventPoints.GetHashCode();
            }

            return hashCode;
        }
    }

    /// <summary>
    /// To validate all properties of the instance
    /// </summary>
    /// <param name="validationContext">Validation context</param>
    /// <returns>Validation Result</returns>
    IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext) => [];
}
