/* 
 * The Blue Alliance API v3
 *
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
 *
 * The version of the OpenAPI document: 3.8.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

namespace TBAAPI.V3Client.Model;

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
/// <summary>
/// DistrictList
/// </summary>
[DataContract]
public partial record DistrictList : IValidatableObject
{
    /// <summary>
    /// The short identifier for the district.
    /// </summary>
    /// <value>The short identifier for the district.</value>
    [DataMember(Name = "abbreviation", EmitDefaultValue = false), JsonPropertyName("abbreviation")]
    public string? Abbreviation { get; set; }

    /// <summary>
    /// The long name for the district.
    /// </summary>
    /// <value>The long name for the district.</value>
    [DataMember(Name = "display_name", EmitDefaultValue = false), JsonPropertyName("display_name")]
    public string? DisplayName { get; set; }

    /// <summary>
    /// Key for this district, e.g. '2016ne'.
    /// </summary>
    /// <value>Key for this district, e.g. '2016ne'.</value>
    [DataMember(Name = "key", EmitDefaultValue = false), JsonPropertyName("key")]
    public string? Key { get; set; }

    /// <summary>
    /// Year this district participated.
    /// </summary>
    /// <value>Year this district participated.</value>
    [DataMember(Name = "year", EmitDefaultValue = false), JsonPropertyName("year")]
    public int Year { get; set; }

    /// <summary>
    /// Returns the string presentation of the object
    /// </summary>
    /// <returns>String presentation of the object</returns>
    public override string ToString()
    {
        var sb = new StringBuilder();
        sb.Append("class DistrictList {\n");
        sb.Append("  Abbreviation: ").Append(this.Abbreviation).Append('\n');
        sb.Append("  DisplayName: ").Append(this.DisplayName).Append('\n');
        sb.Append("  Key: ").Append(this.Key).Append('\n');
        sb.Append("  Year: ").Append(this.Year).Append('\n');
        sb.Append("}\n");
        return sb.ToString();
    }

    /// <summary>
    /// Returns the JSON string presentation of the object
    /// </summary>
    /// <returns>JSON string presentation of the object</returns>
    public virtual string ToJson() => JsonSerializer.Serialize(this, GetType());

    /// <summary>
    /// Gets the hash code
    /// </summary>
    /// <returns>Hash code</returns>
    public override int GetHashCode()
    {
        unchecked // Overflow is fine, just wrap
        {
            var hashCode = 41;
            if (this.Abbreviation is not null)
            {
                hashCode = (hashCode * 59) + this.Abbreviation.GetHashCode();
            }

            if (this.DisplayName is not null)
            {
                hashCode = (hashCode * 59) + this.DisplayName.GetHashCode();
            }

            if (this.Key is not null)
            {
                hashCode = (hashCode * 59) + this.Key.GetHashCode();
            }

            hashCode = (hashCode * 59) + this.Year.GetHashCode();
            return hashCode;
        }
    }

    /// <summary>
    /// To validate all properties of the instance
    /// </summary>
    /// <param name="validationContext">Validation context</param>
    /// <returns>Validation Result</returns>
    IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext) => [];
}
