/* 
 * The Blue Alliance API v3
 *
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
 *
 * The version of the OpenAPI document: 3.8.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

namespace TBAAPI.V3Client.Model;

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
/// <summary>
/// EliminationAllianceStatus
/// </summary>
/// <remarks>
/// Initializes a new instance of the <see cref="EliminationAllianceStatus" /> class.
/// </remarks>
[DataContract]
public partial record EliminationAllianceStatus : IValidatableObject
{

    /// <summary>
    /// Gets or Sets PlayoffAverage
    /// </summary>
    [DataMember(Name = "playoff_average", EmitDefaultValue = false), JsonPropertyName("playoff_average")]
    public double PlayoffAverage { get; set; }

    /// <summary>
    /// Gets or Sets Level
    /// </summary>
    [DataMember(Name = "level", EmitDefaultValue = false), JsonPropertyName("level")]
    public string? Level { get; set; }

    /// <summary>
    /// Gets or Sets Record
    /// </summary>
    [DataMember(Name = "record", EmitDefaultValue = false), JsonPropertyName("record")]
    public WLTRecord? Record { get; set; }

    /// <summary>
    /// Gets or Sets CurrentLevelRecord
    /// </summary>
    [DataMember(Name = "current_level_record", EmitDefaultValue = false), JsonPropertyName("current_level_record")]
    public WLTRecord? CurrentLevelRecord { get; set; }

    /// <summary>
    /// Gets or Sets Status
    /// </summary>
    [DataMember(Name = "status", EmitDefaultValue = false), JsonPropertyName("status")]
    public string? Status { get; set; }

    /// <summary>
    /// Returns the string presentation of the object
    /// </summary>
    /// <returns>String presentation of the object</returns>
    public override string ToString()
    {
        var sb = new StringBuilder();
        sb.Append("class EliminationAllianceStatus {\n");
        sb.Append("  PlayoffAverage: ").Append(this.PlayoffAverage).Append('\n');
        sb.Append("  Level: ").Append(this.Level).Append('\n');
        sb.Append("  Record: ").Append(this.Record).Append('\n');
        sb.Append("  CurrentLevelRecord: ").Append(this.CurrentLevelRecord).Append('\n');
        sb.Append("  Status: ").Append(this.Status).Append('\n');
        sb.Append("}\n");
        return sb.ToString();
    }

    /// <summary>
    /// Returns the JSON string presentation of the object
    /// </summary>
    /// <returns>JSON string presentation of the object</returns>
    public virtual string ToJson() => JsonSerializer.Serialize(this, GetType());

    /// <summary>
    /// Gets the hash code
    /// </summary>
    /// <returns>Hash code</returns>
    public override int GetHashCode() => HashCode.Combine(this.PlayoffAverage, this.Level, this.Record, this.CurrentLevelRecord, this.Status);

    /// <summary>
    /// To validate all properties of the instance
    /// </summary>
    /// <param name="validationContext">Validation context</param>
    /// <returns>Validation Result</returns>
    IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext) => [];
}
