name: yaap-mcp
services:
  mcpserver:
    hostname: mcpserver
    image: ${DOCKER_REGISTRY-}yaap-mcp-server
    build:
      context: .
      dockerfile: AgentsMcpServer/Dockerfile
    environment:
      - ASPNETCORE_HTTP_PORTS=5272
      # - URLS=http://0.0.0.0:5272

  orchestrator:
    hostname: orchestrator
    image: ${DOCKER_REGISTRY-}yaap-mcp-orchestrator
    build:
      context: .
      dockerfile: Agents/WebSockets/Orchestrator_WS/Dockerfile
    environment:
      - McpServerEndpoint=http://mcpserver:5272/sse
      - ASPNETCORE_HTTP_PORTS=5172
      # - URLS=http://0.0.0.0:5172
    ports:
      - "5172:5172"
    depends_on:
      - mcpserver

  teams_agent:
    hostname: teams_agent
    image: ${DOCKER_REGISTRY-}yaap-mcp-teamsagent
    build:
      context: .
      dockerfile: Agents/WebSockets/Teams_WS/Dockerfile
    environment:
      - McpServerEndpoint=ws://mcpserver:5272/ws/register
      - ASPNETCORE_HTTP_PORTS=5173
      # - URLS=http://0.0.0.0:5173
    depends_on:
      - mcpserver
      - orchestrator  

networks:
  default:
