/* 
 * The Blue Alliance API v3
 *
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
 *
 * The version of the OpenAPI document: 3.8.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

namespace TBAAPI.V3Client.Model;

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
/// <summary>
/// EventRankingSortOrderInfo
/// </summary>
[DataContract]
public partial record EventRankingSortOrderInfo : IValidatableObject
{
    /// <summary>
    /// Integer expressing the number of digits of precision in the number provided in 'sort_orders'.
    /// </summary>
    /// <value>Integer expressing the number of digits of precision in the number provided in 'sort_orders'.</value>
    [DataMember(Name = "precision", EmitDefaultValue = false), JsonPropertyName("precision")]
    public int Precision { get; set; }

    /// <summary>
    /// Name of the field used in the 'sort_order' array.
    /// </summary>
    /// <value>Name of the field used in the 'sort_order' array.</value>
    [DataMember(Name = "name", EmitDefaultValue = false), JsonPropertyName("name")]
    public string? Name { get; set; }

    /// <summary>
    /// Returns the string presentation of the object
    /// </summary>
    /// <returns>String presentation of the object</returns>
    public override string ToString()
    {
        var sb = new StringBuilder();
        sb.Append("class EventRankingSortOrderInfo {\n");
        sb.Append("  Precision: ").Append(this.Precision).Append('\n');
        sb.Append("  Name: ").Append(this.Name).Append('\n');
        sb.Append("}\n");
        return sb.ToString();
    }

    /// <summary>
    /// Returns the JSON string presentation of the object
    /// </summary>
    /// <returns>JSON string presentation of the object</returns>
    public virtual string ToJson() => JsonSerializer.Serialize(this, GetType());

    /// <summary>
    /// Gets the hash code
    /// </summary>
    /// <returns>Hash code</returns>
    public override int GetHashCode()
    {
        unchecked // Overflow is fine, just wrap
        {
            var hashCode = 41;
            hashCode = (hashCode * 59) + this.Precision.GetHashCode();
            if (this.Name is not null)
            {
                hashCode = (hashCode * 59) + this.Name.GetHashCode();
            }

            return hashCode;
        }
    }

    /// <summary>
    /// To validate all properties of the instance
    /// </summary>
    /// <param name="validationContext">Validation context</param>
    /// <returns>Validation Result</returns>
    IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext) => [];
}
