/* 
 * The Blue Alliance API v3
 *
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
 *
 * The version of the OpenAPI document: 3.8.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

namespace TBAAPI.V3Client.Model;

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
/// <summary>
/// EventDistrictPoints
/// </summary>
[DataContract]
public partial record EventDistrictPoints : IValidatableObject
{
    /// <summary>
    /// Points gained for each team at the event. Stored as a key-value pair with the team key as the key, and an object describing the points as its value.
    /// </summary>
    /// <value>Points gained for each team at the event. Stored as a key-value pair with the team key as the key, and an object describing the points as its value.</value>
    [DataMember(Name = "points", EmitDefaultValue = false), JsonPropertyName("points")]
    public IDictionary<string, EventDistrictPointsPoints>? Points { get; set; }

    /// <summary>
    /// Tiebreaker values for each team at the event. Stored as a key-value pair with the team key as the key, and an object describing the tiebreaker elements as its value.
    /// </summary>
    /// <value>Tiebreaker values for each team at the event. Stored as a key-value pair with the team key as the key, and an object describing the tiebreaker elements as its value.</value>
    [DataMember(Name = "tiebreakers", EmitDefaultValue = false), JsonPropertyName("tiebreakers")]
    public IDictionary<string, EventDistrictPointsTiebreakers>? Tiebreakers { get; set; }

    /// <summary>
    /// Returns the string presentation of the object
    /// </summary>
    /// <returns>String presentation of the object</returns>
    public override string ToString()
    {
        var sb = new StringBuilder();
        sb.Append("class EventDistrictPoints {\n");
        sb.Append("  Points: ").Append(this.Points).Append('\n');
        sb.Append("  Tiebreakers: ").Append(this.Tiebreakers).Append('\n');
        sb.Append("}\n");
        return sb.ToString();
    }

    /// <summary>
    /// Returns the JSON string presentation of the object
    /// </summary>
    /// <returns>JSON string presentation of the object</returns>
    public virtual string ToJson() => JsonSerializer.Serialize(this, GetType());

    /// <summary>
    /// Gets the hash code
    /// </summary>
    /// <returns>Hash code</returns>
    public override int GetHashCode()
    {
        unchecked // Overflow is fine, just wrap
        {
            var hashCode = 41;
            if (this.Points is not null)
            {
                hashCode = (hashCode * 59) + this.Points.GetHashCode();
            }

            if (this.Tiebreakers is not null)
            {
                hashCode = (hashCode * 59) + this.Tiebreakers.GetHashCode();
            }

            return hashCode;
        }
    }

    /// <summary>
    /// To validate all properties of the instance
    /// </summary>
    /// <param name="validationContext">Validation context</param>
    /// <returns>Validation Result</returns>
    IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext) => [];
}
