/* 
 * The Blue Alliance API v3
 *
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
 *
 * The version of the OpenAPI document: 3.8.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

namespace TBAAPI.V3Client.Model;

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;

/// <summary>
/// APIStatusAppVersion
/// </summary>
[DataContract]
public partial record APIStatusAppVersion : IValidatableObject
{
    /// <summary>
    /// Internal use - Minimum application version required to correctly connect and process data.
    /// </summary>
    /// <value>Internal use - Minimum application version required to correctly connect and process data.</value>
    [DataMember(Name = "min_app_version", EmitDefaultValue = false), JsonPropertyName("min_app_version")]
    public int MinAppVersion { get; set; }

    /// <summary>
    /// Internal use - Latest application version available.
    /// </summary>
    /// <value>Internal use - Latest application version available.</value>
    [DataMember(Name = "latest_app_version", EmitDefaultValue = false), JsonPropertyName("latest_app_version")]
    public int LatestAppVersion { get; set; }

    /// <summary>
    /// Returns the string presentation of the object
    /// </summary>
    /// <returns>String presentation of the object</returns>
    public override string ToString()
    {
        var sb = new StringBuilder();
        sb.Append("class APIStatusAppVersion {\n");
        sb.Append("  MinAppVersion: ").Append(this.MinAppVersion).Append('\n');
        sb.Append("  LatestAppVersion: ").Append(this.LatestAppVersion).Append('\n');
        sb.Append("}\n");
        return sb.ToString();
    }

    /// <summary>
    /// Returns the JSON string presentation of the object
    /// </summary>
    /// <returns>JSON string presentation of the object</returns>
    public virtual string ToJson() => JsonSerializer.Serialize(this, GetType());

    /// <summary>
    /// Gets the hash code
    /// </summary>
    /// <returns>Hash code</returns>
    public override int GetHashCode() => HashCode.Combine(this.MinAppVersion, this.LatestAppVersion);

    /// <summary>
    /// To validate all properties of the instance
    /// </summary>
    /// <param name="validationContext">Validation context</param>
    /// <returns>Validation Result</returns>
    IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext) => [];
}
