/* 
 * The Blue Alliance API v3
 *
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
 *
 * The version of the OpenAPI document: 3.8.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

namespace TBAAPI.V3Client.Model;

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;

/// <summary>
/// TeamEventStatusRank
/// </summary>
/// <remarks>
/// Initializes a new instance of the <see cref="TeamEventStatusRank" /> class.
/// </remarks>
[DataContract]
public partial record TeamEventStatusRank : IValidatableObject
{

    /// <summary>
    /// Number of teams ranked.
    /// </summary>
    /// <value>Number of teams ranked.</value>
    [DataMember(Name = "num_teams", EmitDefaultValue = false), JsonPropertyName("num_teams")]
    public int NumTeams { get; set; }

    /// <summary>
    /// Gets or Sets Ranking
    /// </summary>
    [DataMember(Name = "ranking", EmitDefaultValue = false), JsonPropertyName("ranking")]
    public TeamEventStatusRankRanking? Ranking { get; set; }

    /// <summary>
    /// Ordered list of names corresponding to the elements of the 'sort_orders' array.
    /// </summary>
    /// <value>Ordered list of names corresponding to the elements of the 'sort_orders' array.</value>
    [DataMember(Name = "sort_order_info", EmitDefaultValue = false), JsonPropertyName("sort_order_info")]
    public IList<TeamEventStatusRankSortOrderInfo>? SortOrderInfo { get; set; }

    /// <summary>
    /// Gets or Sets Status
    /// </summary>
    [DataMember(Name = "status", EmitDefaultValue = false), JsonPropertyName("status")]
    public string? Status { get; set; }

    /// <summary>
    /// Returns the string presentation of the object
    /// </summary>
    /// <returns>String presentation of the object</returns>
    public override string ToString()
    {
        var sb = new StringBuilder();
        sb.Append("class TeamEventStatusRank {\n");
        sb.Append("  NumTeams: ").Append(this.NumTeams).Append('\n');
        sb.Append("  Ranking: ").Append(this.Ranking).Append('\n');
        sb.Append("  SortOrderInfo: ").Append(this.SortOrderInfo).Append('\n');
        sb.Append("  Status: ").Append(this.Status).Append('\n');
        sb.Append("}\n");
        return sb.ToString();
    }

    /// <summary>
    /// Returns the JSON string presentation of the object
    /// </summary>
    /// <returns>JSON string presentation of the object</returns>
    public virtual string ToJson() => JsonSerializer.Serialize(this, GetType());

    /// <summary>
    /// Gets the hash code
    /// </summary>
    /// <returns>Hash code</returns>
    public override int GetHashCode()
    {
        unchecked // Overflow is fine, just wrap
        {
            var hashCode = 41;
            hashCode = (hashCode * 59) + this.NumTeams.GetHashCode();
            if (this.Ranking is not null)
            {
                hashCode = (hashCode * 59) + this.Ranking.GetHashCode();
            }

            if (this.SortOrderInfo is not null)
            {
                hashCode = (hashCode * 59) + this.SortOrderInfo.GetHashCode();
            }

            if (this.Status is not null)
            {
                hashCode = (hashCode * 59) + this.Status.GetHashCode();
            }

            return hashCode;
        }
    }

    /// <summary>
    /// To validate all properties of the instance
    /// </summary>
    /// <param name="validationContext">Validation context</param>
    /// <returns>Validation Result</returns>
    IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext) => [];
}
