name: yaap-grpc
services:
  orchestrator:
    image: orchestrator
    ports:
      - "5173:5173"
    networks:
      - default

  teamsagent:
    image: teamsagent
    depends_on:
      - orchestrator
    environment:
    #   - ASPNETCORE_HTTP_PORTS=5000
      - URLS=http://teamsagent:5000
    networks:
      - default

networks:
  default:
